(function(root,factory){const api=factory(typeof require==='function'?require('./math.js'):root.NICUMath);if(typeof module==='object'&&module.exports)module.exports=api;root.NICUDistributions=api;})(typeof self!=='undefined'?self:this,function(M){
'use strict';
function survival(u,fitOrName,mu,sigma2,kappa){const f=typeof fitOrName==='string'?{name:fitOrName,kappa}:fitOrName,name=String(f.name||'Lognormal').toLowerCase(),x=Number(u);if(x<=0)return 1;const mean=M.clampPositive(mu??f.mean),v=Math.max(0,Number(sigma2??f.variance??mean)),k=M.clampPositive(kappa??f.kappa??1.5);
if(name==='exponential')return Math.exp(-x/mean);
if(name==='weibull'){const scale=mean/M.gamma(1+1/k);return Math.exp(-Math.pow(x/M.clampPositive(scale),k));}
if(name==='lognormal'){const tau=Math.sqrt(Math.log(1+v/(mean*mean))),ml=Math.log(mean)-.5*tau*tau;return 1-M.normalCdf((Math.log(x)-ml)/M.clampPositive(tau));}
if(name==='gamma'){const scale=mean/k;return M.regularizedGammaQ(k,x/M.clampPositive(scale));}
if(name==='fisk'){if(k<=1)return 1/(1+Math.pow(x/mean,k));const scale=mean*Math.sin(Math.PI/k)/(Math.PI/k);return 1/(1+Math.pow(x/M.clampPositive(scale),k));}
throw new Error('Unknown LOS distribution: '+f.name);}
function marginalSurvival(x,fit){const n=fit.name.toLowerCase();if(x<=0)return 1;if(n==='exponential')return Math.exp(-x/fit.scale);if(n==='weibull')return Math.exp(-Math.pow(x/fit.scale,fit.kappa));if(n==='lognormal')return 1-M.normalCdf((Math.log(x)-fit.muLog)/fit.tau);if(n==='gamma')return M.regularizedGammaQ(fit.kappa,x/fit.scale);if(n==='fisk')return 1/(1+Math.pow(x/fit.scale,fit.kappa));return NaN;}
function q99(f){const n=f.name.toLowerCase();if(n==='exponential')return -f.scale*Math.log(.01);if(n==='weibull')return f.scale*Math.pow(-Math.log(.01),1/f.kappa);if(n==='lognormal')return Math.exp(f.muLog+f.tau*M.inverseNormalCdf(.99));if(n==='gamma')return M.gammaQuantile(.99,f.kappa,f.scale);if(n==='fisk')return f.scale*Math.pow(99,1/f.kappa);return f.max;}
function kmCurve(records){const clean=records.map(r=>({t:Number(r.los_days??r.los??r.time),event:r.event==null?1:Number(r.event)})).filter(r=>r.t>0&&Number.isFinite(r.t)).sort((a,b)=>a.t-b.t);let atRisk=clean.length,S=1;const out=[{time:0,survival:1}];let i=0;while(i<clean.length){const t=clean[i].t;let d=0,c=0;while(i<clean.length&&clean[i].t===t){if(clean[i].event===0)c++;else d++;i++;}if(atRisk>0&&d>0)S*=1-d/atRisk;out.push({time:t,survival:S});atRisk-=d+c;}return out;}
function empiricalAt(curve,x){let s=1;for(const p of curve){if(p.time>x)break;s=p.survival;}return s;}
function finalize(fit,records){const vals=records.map(r=>Number(r.los_days??r.los??r.time)).filter(x=>x>0),curve=kmCurve(records),max=Math.max(...vals),smax=Math.max(1,Math.floor(Math.min(max,q99(fit))));let se=0,n=0;for(let u=0;u<=smax;u++){const e=empiricalAt(curve,u),p=marginalSurvival(u,fit);if(Number.isFinite(p)){se+=(e-p)**2;n++;}}fit.rmse=Math.sqrt(se/Math.max(1,n));fit.smax=smax;fit.max=max;fit.curve=curve;return fit;}
function fitExponential(records){const x=records.map(r=>Number(r.los_days??r.los??r.time)).filter(v=>v>0),scale=M.mean(x);return finalize({name:'Exponential',scale,mean:scale,variance:scale*scale,kappa:null,logLik:-x.length*Math.log(scale)-M.sum(x)/scale},records);}
function fitLognormal(records){const x=records.map(r=>Number(r.los_days??r.los??r.time)).filter(v=>v>0),l=x.map(Math.log),muLog=M.mean(l),tau=Math.sqrt(M.mean(l.map(v=>(v-muLog)**2)))||1e-6,mean=Math.exp(muLog+.5*tau*tau),variance=(Math.exp(tau*tau)-1)*Math.exp(2*muLog+tau*tau),ll=-M.sum(x.map((v,i)=>Math.log(v*tau*Math.sqrt(2*Math.PI))+.5*((l[i]-muLog)/tau)**2));return finalize({name:'Lognormal',muLog,tau,mean,variance,kappa:null,logLik:ll},records);}
function fitWeibull(records){const x=records.map(r=>Number(r.los_days??r.los??r.time)).filter(v=>v>0),lx=x.map(Math.log),ml=M.mean(lx);let k=1.2/(Math.sqrt(M.variance(x))/M.mean(x)||1);k=Math.min(10,Math.max(.1,k));for(let it=0;it<80;it++){const w=x.map(v=>Math.exp(k*Math.log(v))),sw=M.sum(w),swl=M.sum(w.map((v,i)=>v*lx[i])),swl2=M.sum(w.map((v,i)=>v*lx[i]*lx[i])),g=1/k+ml-swl/sw,gp=-1/(k*k)-(swl2*sw-swl*swl)/(sw*sw),nk=k-g/gp;if(!Number.isFinite(nk)||nk<=.05)nk=(k+.05)/2;if(Math.abs(nk-k)<1e-8)break;k=Math.min(20,nk);}const scale=Math.pow(M.mean(x.map(v=>Math.pow(v,k))),1/k),mean=scale*M.gamma(1+1/k),variance=scale*scale*(M.gamma(1+2/k)-M.gamma(1+1/k)**2),ll=x.length*Math.log(k)-x.length*k*Math.log(scale)+(k-1)*M.sum(lx)-M.sum(x.map(v=>Math.pow(v/scale,k)));return finalize({name:'Weibull',kappa:k,scale,mean,variance,logLik:ll},records);}
function fitGamma(records){const x=records.map(r=>Number(r.los_days??r.los??r.time)).filter(v=>v>0),mean=M.mean(x),s=Math.log(mean)-M.mean(x.map(Math.log));let k=(3-s+Math.sqrt((s-3)**2+24*s))/(12*s||1);k=Math.max(.05,k);for(let i=0;i<80;i++){const g=Math.log(k)-M.digamma(k)-s,gp=1/k-M.trigamma(k),nk=k-g/gp;if(!Number.isFinite(nk)||nk<=.02)break;if(Math.abs(nk-k)<1e-9){k=nk;break;}k=nk;}const scale=mean/k,variance=k*scale*scale,ll=(k-1)*M.sum(x.map(Math.log))-M.sum(x)/scale-x.length*(M.logGamma(k)+k*Math.log(scale));return finalize({name:'Gamma',kappa:k,scale,mean,variance,logLik:ll},records);}
function fitFisk(records){const x=records.map(r=>Number(r.los_days??r.los??r.time)).filter(v=>v>0),lx=x.map(Math.log),lo=Math.log(Math.max(M.quantile(x,.05)/20,1e-4)),hi=Math.log(M.quantile(x,.95)*20);function bestAt(logScale){const scale=Math.exp(logScale);const obj=k=>{let ll=x.length*(Math.log(k)-Math.log(scale))+(k-1)*M.sum(lx.map(v=>v-Math.log(scale)))-2*M.sum(x.map(v=>Math.log1p(Math.pow(v/scale,k))));return-ll;};return M.goldenSectionMin(obj,.15,12,1e-5,100);}const outer=M.goldenSectionMin(ls=>bestAt(ls).value,lo,hi,1e-5,100),scale=Math.exp(outer.x),inner=bestAt(outer.x),k=inner.x;let mean=k>1?scale*(Math.PI/k)/Math.sin(Math.PI/k):M.mean(x),variance=k>2?scale*scale*(2*Math.PI/k)/Math.sin(2*Math.PI/k)-mean*mean:M.variance(x);return finalize({name:'Fisk',kappa:k,scale,mean,variance,logLik:-inner.value},records);}
function fitAll(records){if(!records||records.length<3)throw new Error('At least 3 LOS observations are required for automatic fitting.');const fits=[fitExponential(records),fitWeibull(records),fitLognormal(records),fitGamma(records),fitFisk(records)];fits.sort((a,b)=>a.rmse-b.rmse);return{best:fits[0],fits,km:fits[0].curve};}
return{survival,marginalSurvival,kmCurve,empiricalAt,fitAll,q99};
});