(function(root,factory){const api=factory(typeof require==='function'?require('./math.js'):root.NICUMath,typeof require==='function'?require('./distributions.js'):root.NICUDistributions);if(typeof module==='object'&&module.exports)module.exports=api;root.NICUModel=api;})(typeof self!=='undefined'?self:this,function(M,D){
'use strict';
const PRESETS={'Site 1':{distribution:'Fisk',kappa:1.34,smax:325,rmse:.01},'Site 2':{distribution:'Fisk',kappa:1.54,smax:116,rmse:.03},'Site 3':{distribution:'Exponential',kappa:null,smax:57,rmse:.02},'Site 4':{distribution:'Exponential',kappa:null,smax:61,rmse:.01},'Site 5':{distribution:'Weibull',kappa:.97,smax:52,rmse:.02}};
function group(rows){const g=new Map();rows.forEach(r=>{if(!g.has(r.site))g.set(r.site,[]);g.get(r.site).push({...r});});g.forEach(a=>a.sort((x,y)=>x.day-y.day));return g;}
function siteSettings(site,settings,fits){if(settings.distributionMode==='presets'&&PRESETS[site])return{...settings,...PRESETS[site]};if(settings.distributionMode==='auto'&&fits&&fits[site])return{...settings,distribution:fits[site].name,kappa:fits[site].kappa||1.5,smax:fits[site].smax};return{...settings,distribution:settings.distribution||'Lognormal',kappa:Number(settings.kappa||1.5),smax:Number(settings.smax||60)};}
function applyScenario(rows,s){const a=Number(s.arrivalMultiplier||1),m=Number(s.meanLosMultiplier||1),v=Number(s.varianceMultiplier||1),start=s.scenarioStart||null,end=s.scenarioEnd||null;return rows.map(r=>{const key=r.date||String(r.day),inside=(!start||key>=start)&&(!end||key<=end);return{...r,lambda_t:r.lambda_t*(inside?a:1),mu_t:r.mu_t*(inside?m:1),sigma2_t:r.sigma2_t*(inside?v:1)};});}
function occupancy(rows,settings){const rho=new Array(rows.length).fill(0),smax=Math.max(1,Math.floor(settings.smax));for(let t=0;t<rows.length;t++){let z=0;for(let u=0;u<=Math.min(smax,t);u++){const r=rows[t-u];z+=r.lambda_t*D.survival(u,settings.distribution,r.mu_t,r.sigma2_t,settings.kappa);}rho[t]=z;}return rho;}
function bAverage(rows){const r=M.mean(rows.map(x=>x.lambda_t))*M.mean(rows.map(x=>x.mu_t));return{beds:Math.ceil(r+Math.sqrt(Math.max(0,r))),rhoBar:r};}
function bMax(rho){const p=Math.max(...rho);return Math.ceil(p+Math.sqrt(Math.max(0,p)));}
function overflowRisk(rho,B,gamma,rule){const k=Math.floor(gamma*B),risks=rho.map(x=>1-M.poissonCdf(k,x));return rule==='max daily risk'?Math.max(...risks):M.mean(risks);}
function overflowCapacity(rho,gamma,alpha,rule){let lo=1,hi=Math.max(2,Math.ceil(Math.max(...rho)/Math.max(gamma,.01)));while(overflowRisk(rho,hi,gamma,rule)>alpha&&hi<20000)hi*=2;while(lo<hi){const mid=Math.floor((lo+hi)/2);if(overflowRisk(rho,mid,gamma,rule)<=alpha)hi=mid;else lo=mid+1;}return lo;}
function observedMetrics(rows,capacities){if(!rows.some(r=>Number.isFinite(r.observed_occupancy)))return[];const out=[];for(const[name,B]of Object.entries(capacities)){const u=rows.map(r=>100*Number(r.observed_occupancy||0)/B),over=u.filter(x=>x>100),under=u.filter(x=>x<70);out.push({strategy:name,beds:B,mean_utilization:M.mean(u),sd_utilization:M.std(u,true),pct_days_over_100:100*over.length/u.length,mean_excess_over_100:over.length?M.mean(over.map(x=>x-100)):0,pct_days_under_70:100*under.length/u.length,mean_shortfall_under_70:under.length?M.mean(under.map(x=>70-x)):0});}return out;}
function analyze(rows,settings,fits){const summary=[],daily=[],utilization=[],weights={};for(const[site,raw]of group(rows)){const ss=siteSettings(site,settings,fits),siteRows=applyScenario(raw,settings),rho=occupancy(siteRows,ss),ba=bAverage(siteRows),caps={actual_beds:Number((settings.actualBeds||{})[site])||null,B_average:ba.beds,'B_0.05':overflowCapacity(rho,Number(settings.gamma||1),.05,settings.riskRule||'average daily risk'),'B_0.01':overflowCapacity(rho,Number(settings.gamma||1),.01,settings.riskRule||'average daily risk'),B_max:bMax(rho)},naive=Math.ceil(Math.max(...siteRows.map(r=>r.lambda_t*r.mu_t)));summary.push({site,distribution:ss.distribution,kappa:ss.kappa||null,smax:ss.smax,rho_bar:ba.rhoBar,mean_rho_t:M.mean(rho),peak_rho_t:Math.max(...rho),B_naive_peak:naive,...caps});siteRows.forEach((r,i)=>daily.push({...r,rho_t:rho[i],B_naive_peak:naive,...caps}));weights[site]=M.sum(siteRows.map(r=>Number(r.admission_count??r.lambda_t)));observedMetrics(siteRows,Object.fromEntries(Object.entries(caps).filter(([,v])=>Number.isFinite(v)))).forEach(x=>utilization.push({site,...x}));}const strategies=[...new Set(utilization.map(x=>x.strategy))];for(const strategy of strategies){const a=utilization.filter(x=>x.strategy===strategy&&x.site!=='Weighted system'),W=M.sum(a.map(x=>weights[x.site]||0));if(!W)continue;const wm=M.sum(a.map(x=>(weights[x.site]||0)*x.mean_utilization))/W,ws=Math.sqrt(M.sum(a.map(x=>(weights[x.site]||0)*(x.mean_utilization-wm)**2))/W);utilization.push({site:'Weighted system',strategy,beds:null,mean_utilization:wm,sd_utilization:ws,pct_days_over_100:null,mean_excess_over_100:null,pct_days_under_70:null,mean_shortfall_under_70:null});}return{summary,daily,utilization};}
function sensitivity(rows,settings,fits,betas){const out=[];for(const[site,raw]of group(rows)){const ss=siteSettings(site,settings,fits),baseRho=occupancy(raw,ss),base={'B_0.05':overflowCapacity(baseRho,settings.gamma,.05,settings.riskRule),'B_0.01':overflowCapacity(baseRho,settings.gamma,.01,settings.riskRule),B_max:bMax(baseRho)};for(const beta of betas){const changed=raw.map(r=>({...r,sigma2_t:r.sigma2_t*beta})),rho=occupancy(changed,ss),vals={'B_0.05':overflowCapacity(rho,settings.gamma,.05,settings.riskRule),'B_0.01':overflowCapacity(rho,settings.gamma,.01,settings.riskRule),B_max:bMax(rho)};for(const[k,beds]of Object.entries(vals))out.push({site,strategy:k,beta,beds,pct_change:100*(beds-base[k])/base[k]});}}return out;}
function synthetic(days=365){const cfg=[['Site 1',1.6,.25,8,0],['Site 2',3.2,.2,9.5,20],['Site 3',2.4,.18,8.4,55],['Site 4',2.6,.22,8.6,80],['Site 5',1.5,.2,7.8,120]],out=[];for(const[site,l,a,mu,p]of cfg)for(let t=0;t<days;t++){const la=Math.max(.001,l*(1+a*Math.sin(2*Math.PI*(t+p)/365))),m=Math.max(.01,mu*(1+.1*Math.sin(2*Math.PI*(t+60+p)/365)));out.push({site,day:t+1,date:null,year:null,day_of_year:t+1,lambda_t:la,mu_t:m,sigma2_t:m*m,observed_occupancy:null,admission_count:la});}return out;}
return{PRESETS,siteSettings,applyScenario,occupancy,bAverage,bMax,overflowCapacity,analyze,sensitivity,synthetic,group};
});