(function(root,factory){const api=factory(typeof require==='function'?require('./math.js'):root.NICUMath);if(typeof module==='object'&&module.exports)module.exports=api;root.NICUPreprocessing=api;})(typeof self!=='undefined'?self:this,function(M){
'use strict';
function localPoly(series,window,degree=1,robust=false){const n=series.length,w=Math.max(3,Math.floor(window)|1),half=Math.floor(w/2),out=new Array(n),rob=new Array(n).fill(1);for(let pass=0;pass<(robust?3:1);pass++){for(let i=0;i<n;i++){const lo=Math.max(0,i-half),hi=Math.min(n-1,i+half),A=Array.from({length:degree+1},()=>new Array(degree+1).fill(0)),b=new Array(degree+1).fill(0),maxD=Math.max(1,Math.max(i-lo,hi-i));for(let j=lo;j<=hi;j++){if(!Number.isFinite(series[j]))continue;const x=j-i,u=Math.abs(x)/maxD,wt=(u<1?Math.pow(1-u**3,3):0)*rob[j];let xp=[1];for(let p=1;p<=2*degree;p++)xp[p]=xp[p-1]*x;for(let r=0;r<=degree;r++){b[r]+=wt*series[j]*xp[r];for(let c=0;c<=degree;c++)A[r][c]+=wt*xp[r+c];}}out[i]=M.solveLinear(A,b)[0];}if(robust&&pass<2){const res=series.map((v,i)=>Math.abs(v-out[i])).filter(Number.isFinite),med=M.median(res)||1;for(let i=0;i<n;i++){const u=Math.abs(series[i]-out[i])/(6*med);rob[i]=u>=1?0:Math.pow(1-u*u,2);}}}return out;}
function seasonalComponent(series,trend,period=7,window=7,degree=1,robust=false){const detr=series.map((v,i)=>v-trend[i]),season=new Array(series.length).fill(0);for(let phase=0;phase<period;phase++){const idx=[],sub=[];for(let i=phase;i<series.length;i+=period){idx.push(i);sub.push(detr[i]);}const sw=Math.max(3,Math.round(window/period)*2+1),sm=localPoly(sub,sw,degree,robust);idx.forEach((id,j)=>season[id]=sm[j]);}const center=M.mean(season);return season.map(v=>v-center);}
function stlApprox(series,cfg){let trend=localPoly(series,cfg.trendWindow,cfg.trendDegree,cfg.robust),season=seasonalComponent(series,trend,7,cfg.seasonalWindow,cfg.seasonalDegree,cfg.robust),adjusted=series.map((v,i)=>v-season[i]);trend=localPoly(adjusted,cfg.trendWindow,cfg.trendDegree,cfg.robust);season=seasonalComponent(series,trend,7,cfg.seasonalWindow,cfg.seasonalDegree,cfg.robust);const residual=series.map((v,i)=>v-trend[i]-season[i]);return{trend,seasonal:season,residual,score:M.std(residual)};}
function chooseStl(series,mode='preset'){const preset={seasonalWindow:7,trendWindow:15,seasonalDegree:1,trendDegree:1,robust:false};if(mode!=='grid')return{config:preset,...stlApprox(series,preset)};let best=null;for(const sw of[7,15,31])for(const tw of[15,31,61])for(const sd of[1,2])for(const td of[1,2])for(const robust of[false,true]){const config={seasonalWindow:sw,trendWindow:tw,seasonalDegree:sd,trendDegree:td,robust},r=stlApprox(series,config);if(!best||r.score<best.score)best={config,...r};}return best;}
function rollingVariance(residual,window=31){const n=residual.length,h=Math.floor(window/2),out=[];for(let i=0;i<n;i++){const a=residual.slice(Math.max(0,i-h),Math.min(n,i+h+1)).filter(Number.isFinite);out.push(Math.max(1e-6,M.variance(a,true)));}return out;}
function fillMissing(a){const out=a.slice();let last=null;for(let i=0;i<out.length;i++){if(Number.isFinite(out[i]))last=out[i];else if(last!=null)out[i]=last;}last=null;for(let i=out.length-1;i>=0;i--){if(Number.isFinite(out[i]))last=out[i];else if(last!=null)out[i]=last;}const fallback=M.mean(out.filter(Number.isFinite))||1;return out.map(v=>Number.isFinite(v)?v:fallback);}
function normalizeRaw(rows){const out=[];for(const r of rows){const site=String(r.site??r.institution??'Site 1').trim(),ad=M.dateKey(r.admission_date??r.admit_date??r.date),los=Number(r.los_days??r.los??r.length_of_stay),dis=M.dateKey(r.discharge_date),event=r.event==null?1:Number(r.event);if(site&&ad&&los>0)out.push({site,admission_date:ad,discharge_date:dis,los_days:los,event});}if(!out.length)throw new Error('Raw CSV needs site, admission_date, and los_days columns.');return out.sort((a,b)=>a.site.localeCompare(b.site)||a.admission_date.localeCompare(b.admission_date));}
function reconstructObserved(raw,start,end){const map=new Map();for(const r of raw){const discharge=r.discharge_date||M.addDays(r.admission_date,Math.max(1,Math.ceil(r.los_days)));for(let d=r.admission_date;d<discharge&&d<=end;d=M.addDays(d,1)){if(d<start)continue;map.set(d,(map.get(d)||0)+1);}}return map;}
function processRawAdmissions(input,options={}){const raw=normalizeRaw(input),groups=new Map();raw.forEach(r=>{if(!groups.has(r.site))groups.set(r.site,[]);groups.get(r.site).push(r);});const daily=[],fitsInput={},configs=[];for(const[site,records]of groups){const start=records[0].admission_date,end=records.reduce((m,r)=>r.admission_date>m?r.admission_date:m,start),n=M.daysBetween(start,end)+1,byDate=new Map();records.forEach(r=>{if(!byDate.has(r.admission_date))byDate.set(r.admission_date,[]);byDate.get(r.admission_date).push(r.los_days);});const counts=[],means=[],dates=[];for(let i=0;i<n;i++){const date=M.addDays(start,i),vals=byDate.get(date)||[];dates.push(date);counts.push(vals.length);means.push(vals.length?M.mean(vals):NaN);}const filled=fillMissing(means),adm=chooseStl(counts,options.stlMode||'preset'),los=chooseStl(filled,options.stlMode||'preset'),sigma2=rollingVariance(los.residual,Number(options.rollingWindow||31)),obs=reconstructObserved(records,start,end);for(let i=0;i<n;i++)daily.push({site,day:i+1,date:dates[i],year:Number(dates[i].slice(0,4)),day_of_year:M.dayOfYear(dates[i]),lambda_t:Math.max(0,adm.trend[i]+adm.seasonal[i]),mu_t:Math.max(.01,los.trend[i]+los.seasonal[i]),sigma2_t:sigma2[i],observed_occupancy:obs.get(dates[i])||0,admission_count:counts[i]});fitsInput[site]=records;configs.push({site,admission_score:adm.score,los_score:los.score,seasonal_window:adm.config.seasonalWindow,trend_window:adm.config.trendWindow,seasonal_degree:adm.config.seasonalDegree,trend_degree:adm.config.trendDegree,robust:adm.config.robust,rolling_window:Number(options.rollingWindow||31)});}return{daily,raw,fitsInput,configs};}
function validateProcessed(rows){const out=[];for(const r of rows){const site=String(r.site||'Site 1'),day=Number(r.day),lambda=Number(r.lambda_t),mu=Number(r.mu_t),v=Number(r.sigma2_t),date=M.dateKey(r.date),year=Number(r.year||(date?date.slice(0,4):NaN)),doy=Number(r.day_of_year||(date?M.dayOfYear(date):day)),obs=Number(r.observed_occupancy);if(Number.isFinite(day)&&lambda>=0&&mu>0&&v>=0)out.push({site,day,lambda_t:lambda,mu_t:mu,sigma2_t:v,date:date||null,year:Number.isFinite(year)?year:null,day_of_year:Number.isFinite(doy)?doy:day,observed_occupancy:Number.isFinite(obs)?obs:null,admission_count:Number(r.admission_count)||lambda});}if(!out.length)throw new Error('Processed CSV needs site, day, lambda_t, mu_t, sigma2_t.');return out.sort((a,b)=>a.site.localeCompare(b.site)||a.day-b.day);}
return{localPoly,stlApprox,chooseStl,rollingVariance,normalizeRaw,processRawAdmissions,validateProcessed};
});