(function(root,factory){const api=factory(typeof require==='function'?require('./math.js'):root.NICUMath,typeof require==='function'?require('./model.js'):root.NICUModel);if(typeof module==='object'&&module.exports)module.exports=api;root.NICUProjections=api;})(typeof self!=='undefined'?self:this,function(M,Model){
'use strict';
function validateBirths(rows){const out=rows.map(r=>({year:Number(r.year),births:Number(r.births??r.projected_births)})).filter(r=>Number.isInteger(r.year)&&r.births>0).sort((a,b)=>a.year-b.year);if(!out.length)throw new Error('Birth projection CSV needs year and births.');return out;}
function historicalPatterns(rows){const map=new Map();for(const r of rows){if(!Number.isFinite(r.year))continue;const key=r.site+'|'+r.year;if(!map.has(key))map.set(key,[]);map.get(key).push(r);}map.forEach(a=>a.sort((x,y)=>x.day_of_year-y.day_of_year));return map;}
function annualAdmissions(rows){const m=new Map();for(const r of rows){if(!Number.isFinite(r.year))continue;const k=r.site+'|'+r.year;m.set(k,(m.get(k)||0)+Number(r.admission_count??r.lambda_t));}return m;}
function summarize(vals){const s=vals.slice().sort((a,b)=>a-b);return{median:M.quantile(s,.5),q1:M.quantile(s,.25),q3:M.quantile(s,.75),mean:M.mean(s),sd:M.std(s,true)};}
function run(rows,birthRows,settings,fits,options={}){const births=validateBirths(birthRows),patterns=historicalPatterns(rows),annual=annualAdmissions(rows),sites=[...new Set(rows.map(r=>r.site))],yearsAvail=[...new Set(rows.map(r=>r.year).filter(Number.isFinite))].sort(),baseYears=(options.baselineYears||[2021,2022,2023]).filter(y=>yearsAvail.includes(y)),patternYears=(options.patternYears||yearsAvail),runs=Math.min(300,Math.max(1,Number(options.runs||100))),eta=Number(options.eta??1),psi=Number(options.psi??1),rng=M.mulberry32(Number(options.seed||2025));if(!baseYears.length||!patternYears.length)throw new Error('Projection requires processed data with multiple historical years or raw admissions processed into dated daily inputs.');
const systemByYear=new Map();for(const y of baseYears){let total=0;for(const site of sites)total+=annual.get(site+'|'+y)||0;systemByYear.set(y,total);}const Abase=M.mean([...systemByYear.values()]),shares={};for(const site of sites)shares[site]=M.mean(baseYears.map(y=>(annual.get(site+'|'+y)||0)/(systemByYear.get(y)||1)));const y0=births[0].year,K0=births[0].births,cache=new Map();
function pair(site,ay,ly){const key=[site,ay,ly].join('|');if(cache.has(key))return cache.get(key);const ar=(patterns.get(site+'|'+ay)||[]),lr=(patterns.get(site+'|'+ly)||[]);if(!ar.length||!lr.length)return null;const n=365,lam=new Array(n).fill(0),mu=new Array(n).fill(M.mean(lr.map(r=>r.mu_t))),v=new Array(n).fill(M.mean(lr.map(r=>r.sigma2_t)));ar.forEach(r=>{const i=Math.min(364,Math.max(0,(r.day_of_year||1)-1));lam[i]+=Number(r.lambda_t);});lr.forEach(r=>{const i=Math.min(364,Math.max(0,(r.day_of_year||1)-1));mu[i]=r.mu_t;v[i]=r.sigma2_t;});const total=M.sum(lam)||1,unit=lam.map(x=>x/total),rows365=unit.map((x,i)=>({site,day:i+1,lambda_t:x,mu_t:mu[i],sigma2_t:v[i]})),ss=Model.siteSettings(site,settings,fits),rhoUnit=Model.occupancy(rows365,ss),obj={rows365,rhoUnit,meanMu:M.mean(mu)};cache.set(key,obj);return obj;}
const results=[];for(let r=1;r<=runs;r++)for(const b of births){const A=Abase*Math.pow(b.births/K0,eta)*Math.pow(psi,b.year-y0);for(const site of sites){const valid=patternYears.filter(y=>patterns.has(site+'|'+y));if(!valid.length)continue;const ay=valid[Math.floor(rng()*valid.length)],ly=valid[Math.floor(rng()*valid.length)],p=pair(site,ay,ly),target=A*shares[site],rho=p.rhoUnit.map(x=>x*target),daily=p.rows365.map(x=>({...x,lambda_t:x.lambda_t*target})),ba=Model.bAverage(daily);results.push({run:r,year:b.year,site,B_average:ba.beds,'B_0.05':Model.overflowCapacity(rho,settings.gamma,.05,settings.riskRule),'B_0.01':Model.overflowCapacity(rho,settings.gamma,.01,settings.riskRule),B_max:Model.bMax(rho),arrival_pattern_year:ay,los_pattern_year:ly});}}
const summary=[];for(const y of births.map(x=>x.year))for(const site of sites){const a=results.filter(x=>x.year===y&&x.site===site);if(!a.length)continue;const row={year:y,site};for(const k of['B_average','B_0.05','B_0.01','B_max']){const s=summarize(a.map(x=>x[k]));row[k+'_median']=s.median;row[k+'_q1']=s.q1;row[k+'_q3']=s.q3;row[k+'_mean']=s.mean;row[k+'_sd']=s.sd;}summary.push(row);}return{results,summary,meta:{runs,eta,psi,Abase,shares,baseYears,patternYears}};}
return{validateBirths,run};
});